### ISSUE TITLE
Fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by merkys** [jsspencer/libcif#5]
Standard build sequence
```
aclocal    # version 1.15
autoheader # version 2.69
autoconf   # version 2.69
./configure
```
fails after ``./configure`` with the following output:
```
configure: error: cannot find install-sh, install.sh, or shtool in config/gnu "."/config/gnu
```

**Comment by blokhin** [comment]
In general, build process is a bit cumbersome. This worked for me in Cygwin / Windows 8.1:
```
autoreconf --install
autoconf
./configure
```
_etc._

However, the library does not seem to be functional at all.

**Comment by merkys** [comment]
Thanks, @blokhin, this worked for me!
